on:
  push:
    branches:
      - "master"






#steps:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: "docker hub login"
        run: docker login --username ${{secrete.USER_NAME}} --password ${{secrete.DOCKER_TOKEN}}

   