on:
  push:
    branches:
      - "master"






#steps:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "test files path"
        run: pwd
      - name: "test printing"
        run: echo mohamed
