on:
  push:
    branches:
      - "master"






#steps:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "test files path"
        run: pwd
      - name: "test printing"
        run: echo mohamed
      - name: "before list the files"
        run: ls

      - uses: actions/checkout@v3

      - name: "after list the files"
        run: ls -a